// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/service/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServiceStatus int32

const (
	HealthCheckResponse_SERVICE_STATUS_UNSPECIFIED HealthCheckResponse_ServiceStatus = 0
	HealthCheckResponse_SERVICE_STATUS_OK          HealthCheckResponse_ServiceStatus = 1
	HealthCheckResponse_SERVICE_STATUS_UNINIT      HealthCheckResponse_ServiceStatus = 2
	HealthCheckResponse_SERVICE_STATUS_ERROR       HealthCheckResponse_ServiceStatus = 3
)

// Enum value maps for HealthCheckResponse_ServiceStatus.
var (
	HealthCheckResponse_ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_OK",
		2: "SERVICE_STATUS_UNINIT",
		3: "SERVICE_STATUS_ERROR",
	}
	HealthCheckResponse_ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_STATUS_OK":          1,
		"SERVICE_STATUS_UNINIT":      2,
		"SERVICE_STATUS_ERROR":       3,
	}
)

func (x HealthCheckResponse_ServiceStatus) Enum() *HealthCheckResponse_ServiceStatus {
	p := new(HealthCheckResponse_ServiceStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_service_common_common_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServiceStatus) Type() protoreflect.EnumType {
	return &file_protos_service_common_common_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServiceStatus.Descriptor instead.
func (HealthCheckResponse_ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_service_common_common_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_protos_service_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.HealthCheckResponse_ServiceStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_protos_service_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServiceStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVICE_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_service_common_common_proto protoreflect.FileDescriptor

const file_protos_service_common_common_proto_rawDesc = "" +
	"\n" +
	"\"protos/service/common/common.proto\x12\x06common\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xef\x01\n" +
	"\x13HealthCheckResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).common.HealthCheckResponse.ServiceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SERVICE_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15SERVICE_STATUS_UNINIT\x10\x02\x12\x18\n" +
	"\x14SERVICE_STATUS_ERROR\x10\x032J\n" +
	"\x06Health\x12@\n" +
	"\x05Check\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponseBKZFgithub.com/sunzhenkai/kung-fu-panda-protocols/go/service/common;common\x80\x01\x01b\x06proto3"

var (
	file_protos_service_common_common_proto_rawDescOnce sync.Once
	file_protos_service_common_common_proto_rawDescData []byte
)

func file_protos_service_common_common_proto_rawDescGZIP() []byte {
	file_protos_service_common_common_proto_rawDescOnce.Do(func() {
		file_protos_service_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_service_common_common_proto_rawDesc), len(file_protos_service_common_common_proto_rawDesc)))
	})
	return file_protos_service_common_common_proto_rawDescData
}

var file_protos_service_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_service_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_service_common_common_proto_goTypes = []any{
	(HealthCheckResponse_ServiceStatus)(0), // 0: common.HealthCheckResponse.ServiceStatus
	(*HealthCheckRequest)(nil),             // 1: common.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: common.HealthCheckResponse
}
var file_protos_service_common_common_proto_depIdxs = []int32{
	0, // 0: common.HealthCheckResponse.status:type_name -> common.HealthCheckResponse.ServiceStatus
	1, // 1: common.Health.Check:input_type -> common.HealthCheckRequest
	2, // 2: common.Health.Check:output_type -> common.HealthCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_service_common_common_proto_init() }
func file_protos_service_common_common_proto_init() {
	if File_protos_service_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_service_common_common_proto_rawDesc), len(file_protos_service_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_common_common_proto_goTypes,
		DependencyIndexes: file_protos_service_common_common_proto_depIdxs,
		EnumInfos:         file_protos_service_common_common_proto_enumTypes,
		MessageInfos:      file_protos_service_common_common_proto_msgTypes,
	}.Build()
	File_protos_service_common_common_proto = out.File
	file_protos_service_common_common_proto_goTypes = nil
	file_protos_service_common_common_proto_depIdxs = nil
}
