// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: protos/dumper/http.proto

package dumper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Full   string `protobuf:"bytes,1,opt,name=full,proto3" json:"full,omitempty"`
	Schema string `protobuf:"bytes,100,opt,name=schema,proto3" json:"schema,omitempty"`
	Host   string `protobuf:"bytes,101,opt,name=host,proto3" json:"host,omitempty"`
	Port   int32  `protobuf:"varint,102,opt,name=port,proto3" json:"port,omitempty"`
	Path   string `protobuf:"bytes,103,opt,name=path,proto3" json:"path,omitempty"`
	Query  string `protobuf:"bytes,104,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *URI) Reset() {
	*x = URI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dumper_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URI) ProtoMessage() {}

func (x *URI) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dumper_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URI.ProtoReflect.Descriptor instead.
func (*URI) Descriptor() ([]byte, []int) {
	return file_protos_dumper_http_proto_rawDescGZIP(), []int{0}
}

func (x *URI) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *URI) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *URI) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *URI) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *URI) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *URI) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type HttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri  *URI   `protobuf:"bytes,100,opt,name=uri,proto3" json:"uri,omitempty"`
	Body []byte `protobuf:"bytes,150,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dumper_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dumper_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_protos_dumper_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpRequest) GetUri() *URI {
	if x != nil {
		return x.Uri
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_protos_dumper_http_proto protoreflect.FileDescriptor

var file_protos_dumper_http_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x65, 0x72, 0x2f,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x75, 0x6d, 0x70,
	0x65, 0x72, 0x22, 0x83, 0x01, 0x0a, 0x03, 0x55, 0x52, 0x49, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75,
	0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x65,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x66, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x67, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x68, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x0b, 0x48, 0x74, 0x74, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x64,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x52,
	0x49, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x13, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x96,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x40, 0x5a, 0x3e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6e, 0x7a, 0x68, 0x65,
	0x6e, 0x6b, 0x61, 0x69, 0x2f, 0x6b, 0x75, 0x6e, 0x67, 0x2d, 0x66, 0x75, 0x2d, 0x70, 0x61, 0x6e,
	0x64, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x6f, 0x2f,
	0x64, 0x75, 0x6d, 0x70, 0x65, 0x72, 0x3b, 0x64, 0x75, 0x6d, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_dumper_http_proto_rawDescOnce sync.Once
	file_protos_dumper_http_proto_rawDescData = file_protos_dumper_http_proto_rawDesc
)

func file_protos_dumper_http_proto_rawDescGZIP() []byte {
	file_protos_dumper_http_proto_rawDescOnce.Do(func() {
		file_protos_dumper_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_dumper_http_proto_rawDescData)
	})
	return file_protos_dumper_http_proto_rawDescData
}

var file_protos_dumper_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_dumper_http_proto_goTypes = []interface{}{
	(*URI)(nil),         // 0: dumper.URI
	(*HttpRequest)(nil), // 1: dumper.HttpRequest
}
var file_protos_dumper_http_proto_depIdxs = []int32{
	0, // 0: dumper.HttpRequest.uri:type_name -> dumper.URI
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_dumper_http_proto_init() }
func file_protos_dumper_http_proto_init() {
	if File_protos_dumper_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_dumper_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_dumper_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_dumper_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_dumper_http_proto_goTypes,
		DependencyIndexes: file_protos_dumper_http_proto_depIdxs,
		MessageInfos:      file_protos_dumper_http_proto_msgTypes,
	}.Build()
	File_protos_dumper_http_proto = out.File
	file_protos_dumper_http_proto_rawDesc = nil
	file_protos_dumper_http_proto_goTypes = nil
	file_protos_dumper_http_proto_depIdxs = nil
}
