// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: protos/service/kfpanda/kfpanda.proto

package kfpanda

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KfPandaService_Record_FullMethodName = "/kfpanda.KfPandaService/Record"
	KfPandaService_Replay_FullMethodName = "/kfpanda.KfPandaService/Replay"
)

// KfPandaServiceClient is the client API for KfPandaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KfPandaServiceClient interface {
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
}

type kfPandaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKfPandaServiceClient(cc grpc.ClientConnInterface) KfPandaServiceClient {
	return &kfPandaServiceClient{cc}
}

func (c *kfPandaServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, KfPandaService_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kfPandaServiceClient) Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, KfPandaService_Replay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KfPandaServiceServer is the server API for KfPandaService service.
// All implementations must embed UnimplementedKfPandaServiceServer
// for forward compatibility.
type KfPandaServiceServer interface {
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	Replay(context.Context, *ReplayRequest) (*ReplayResponse, error)
	mustEmbedUnimplementedKfPandaServiceServer()
}

// UnimplementedKfPandaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKfPandaServiceServer struct{}

func (UnimplementedKfPandaServiceServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedKfPandaServiceServer) Replay(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replay not implemented")
}
func (UnimplementedKfPandaServiceServer) mustEmbedUnimplementedKfPandaServiceServer() {}
func (UnimplementedKfPandaServiceServer) testEmbeddedByValue()                        {}

// UnsafeKfPandaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KfPandaServiceServer will
// result in compilation errors.
type UnsafeKfPandaServiceServer interface {
	mustEmbedUnimplementedKfPandaServiceServer()
}

func RegisterKfPandaServiceServer(s grpc.ServiceRegistrar, srv KfPandaServiceServer) {
	// If the following call pancis, it indicates UnimplementedKfPandaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KfPandaService_ServiceDesc, srv)
}

func _KfPandaService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KfPandaServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KfPandaService_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KfPandaServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KfPandaService_Replay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KfPandaServiceServer).Replay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KfPandaService_Replay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KfPandaServiceServer).Replay(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KfPandaService_ServiceDesc is the grpc.ServiceDesc for KfPandaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KfPandaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kfpanda.KfPandaService",
	HandlerType: (*KfPandaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _KfPandaService_Record_Handler,
		},
		{
			MethodName: "Replay",
			Handler:    _KfPandaService_Replay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/service/kfpanda/kfpanda.proto",
}
