// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/service/kfpanda/kfpanda.proto

package kfpanda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_RECORD_TYPE_HTTP        RecordType = 1
	RecordType_RECORD_TYPE_GRPC        RecordType = 2
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_HTTP",
		2: "RECORD_TYPE_GRPC",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"RECORD_TYPE_HTTP":        1,
		"RECORD_TYPE_GRPC":        2,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_service_kfpanda_kfpanda_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_protos_service_kfpanda_kfpanda_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_protos_service_kfpanda_kfpanda_proto_rawDescGZIP(), []int{0}
}

type RecordRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// reqeust timestamp in millisecond
	// default: current timestamp if not set
	TimestampMs   int64  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Service       string `protobuf:"bytes,100,opt,name=service,proto3" json:"service,omitempty"`
	Data          []byte `protobuf:"bytes,101,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_protos_service_kfpanda_kfpanda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_kfpanda_kfpanda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_kfpanda_kfpanda_proto_rawDescGZIP(), []int{0}
}

func (x *RecordRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecordRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RecordRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RecordRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code: indicte the processing result
	// 0: ok, failed otherwise
	Code          int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_protos_service_kfpanda_kfpanda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_kfpanda_kfpanda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_kfpanda_kfpanda_proto_rawDescGZIP(), []int{1}
}

func (x *RecordResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_service_kfpanda_kfpanda_proto protoreflect.FileDescriptor

const file_protos_service_kfpanda_kfpanda_proto_rawDesc = "" +
	"\n" +
	"$protos/service/kfpanda/kfpanda.proto\x12\akfpanda\"\x7f\n" +
	"\rRecordRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x18\n" +
	"\aservice\x18d \x01(\tR\aservice\x12\x12\n" +
	"\x04data\x18e \x01(\fR\x04data\">\n" +
	"\x0eRecordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*U\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RECORD_TYPE_HTTP\x10\x01\x12\x14\n" +
	"\x10RECORD_TYPE_GRPC\x10\x022M\n" +
	"\x0eKfPandaService\x12;\n" +
	"\x06Record\x12\x16.kfpanda.RecordRequest\x1a\x17.kfpanda.RecordResponse\"\x00BMZHgithub.com/sunzhenkai/kung-fu-panda-protocols/go/service/kfpanda;kfpanda\x80\x01\x01b\x06proto3"

var (
	file_protos_service_kfpanda_kfpanda_proto_rawDescOnce sync.Once
	file_protos_service_kfpanda_kfpanda_proto_rawDescData []byte
)

func file_protos_service_kfpanda_kfpanda_proto_rawDescGZIP() []byte {
	file_protos_service_kfpanda_kfpanda_proto_rawDescOnce.Do(func() {
		file_protos_service_kfpanda_kfpanda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_service_kfpanda_kfpanda_proto_rawDesc), len(file_protos_service_kfpanda_kfpanda_proto_rawDesc)))
	})
	return file_protos_service_kfpanda_kfpanda_proto_rawDescData
}

var file_protos_service_kfpanda_kfpanda_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_service_kfpanda_kfpanda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_service_kfpanda_kfpanda_proto_goTypes = []any{
	(RecordType)(0),        // 0: kfpanda.RecordType
	(*RecordRequest)(nil),  // 1: kfpanda.RecordRequest
	(*RecordResponse)(nil), // 2: kfpanda.RecordResponse
}
var file_protos_service_kfpanda_kfpanda_proto_depIdxs = []int32{
	1, // 0: kfpanda.KfPandaService.Record:input_type -> kfpanda.RecordRequest
	2, // 1: kfpanda.KfPandaService.Record:output_type -> kfpanda.RecordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_service_kfpanda_kfpanda_proto_init() }
func file_protos_service_kfpanda_kfpanda_proto_init() {
	if File_protos_service_kfpanda_kfpanda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_service_kfpanda_kfpanda_proto_rawDesc), len(file_protos_service_kfpanda_kfpanda_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_kfpanda_kfpanda_proto_goTypes,
		DependencyIndexes: file_protos_service_kfpanda_kfpanda_proto_depIdxs,
		EnumInfos:         file_protos_service_kfpanda_kfpanda_proto_enumTypes,
		MessageInfos:      file_protos_service_kfpanda_kfpanda_proto_msgTypes,
	}.Build()
	File_protos_service_kfpanda_kfpanda_proto = out.File
	file_protos_service_kfpanda_kfpanda_proto_goTypes = nil
	file_protos_service_kfpanda_kfpanda_proto_depIdxs = nil
}
